### ISSUE TITLE
Date format?

### ISSUE THREAD

**Issue by Petruchio96** [FuLoRi/Analyze-LastPassVaultGUI#1]
Just tried your script after listening to Steve on Security Now, thanks for providing this for us! One question, what is the date format for the "Last Touched" field? I have dates listed like '1562184788' in my csv file and I don't know what format that is in.

**Comment by FuLoRi** [comment]
You're welcome! :) I suspect it's a UNIX epoch timestamp. There's a web-based converter here: https://www.epochconverter.com/.

**Comment by Petruchio96** [comment]
That's exactly what it is, thanks! I completely forgot about Unix Epoch time, it's been a few years (decades?) that I've messed with that.
