### ISSUE TITLE
XML parse error if account has custom_js

### ISSUE THREAD

**Issue by john-aws** [FuLoRi/Analyze-LastPassVaultGUI#3]
Hi, first of all I want to applaud your efforts to help the community. Thank you!

I hit a minor bug when running the script against my vault's XML on Windows 10 (PSVersion=5.1.19041.2364):

```
Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "An error occurred while parsing
EntityName. Line 490, position 100."
At C:\Users\me\Downloads\Analyze-LastPassVault.ps1:315 char:17
+                 [xml]$xml = Get-Content -Path $InFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument
```

This appears to relate to an XML account entry that includes the following:

```
custom_js="if (lploc==3) { var _i = document.getElementById('txtLoginId'); if (_i && _i.form && _i.form.id=='form1' && _i.tagName == "
                INPUT" ) { _i.value = lpcurruser; } } "
````

Deleting that `custom_js` attribute from the XML allows the re-run script to move past that account. In my case, I had to clean up a dozen accounts to remove their non-empty custom_js attributes. Note that the custom JavaScript content varied from account entry to entry.

Once all non-empty custom_js attributes were removed, the parse completed and generated the expected CSV output file.

The parsing error appears to be caused by the presence of the literal `&` in the custom JavaScript. An XML linter reports an issue here:

> The entity name must immediately follow the '&' in the entity reference.xml(NameRequiredInReference)

So, it's possible that LastPass is emitting invalid XML and the PowerShell XML parser is working correctly. However, I  wonder if the script could be enhanced to simply filter out all `custom_js` attributes prior to the XML parse to work around this issue?

**Comment by FuLoRi** [comment]
Hi @john-aws,

Thank you for bringing this to my attention!

Based on what you've discovered, I think you're right that the XML from LastPass is likely invalid. If I can update the Analyze button action to first import the contents of the file into a variable and then run a regex against that variable to remove all custom_js attributes before converting it to XML, that should solve the issue.

I didn't have any custom_js in my vault. Could you supply me with a sanitized example (i.e., with dummy values) of an account containing custom javascript so that I can build the appropriate regex?

Thank you again!

**Comment by john-aws** [comment]
Here's a standalone, redacted account XML for a fictitious WebEx account:

```xml
<response>
    <accounts accts_version="123" updated_enc="1"
        encrypted_username="redacted" cbc="1" pd="123456789" eu="1">
        <account name="redacted" urid="0" id="1234567890"
            url="68747470733a2f2f77656273657276696365732e77656265782e636f6d2f6d77333030302f6d7977656265782f64656661756c742e646f3f7369746575726c3d7765627365727669636573"
            m="1" http="0" fav="0" favico="0" autologin="0" basic_auth="0"
            group="redacted" fiid="1234567890" genpw="0"
            extra="" isbookmark="0" never_autofill="0" last_touch="1600000000"
            last_modified="1600000000" sn="0" realm="" sharedfromaid="" pwprotect="0"
            launch_count="0" username="redacted"
            groupid="78">
            <login urid="0"
                url="68747470733a2f2f77656273657276696365732e77656265782e636f6d2f6d77333030302f6d7977656265782f64656661756c742e646f3f7369746575726c3d7765627365727669636573"
                submit_id="" captcha_id=""
                custom_js=" if(lploc==3){ var __u = document.getElementById('username'); var __f = document.getElementById('loginForm'); if (__u && __f && __u.tagName=='INPUT' && __f.tagName=='DIV' && typeof(lpcurruser)!='undefined') { __u.value = lpcurruser; } }"
                u="redacted"
                p="redacted" o="" method="post">
                <field name="screenName" type="text"
                    value="redacted" />
                <field name="email" type="text"
                    value="redacted" />
            </login>
        </account>
    </accounts>
</response>
```

XML parsing will fail at line 15 (the `custom_js` attribute). Removing that attribute (or setting its value to empty string) and re-parsing will succeed.

There is also an option to correctly escape the ampersand (replace the character `&` with `&#038;`) but I don't think that's needed, and may accidentally introduce other issues.

**Comment by john-aws** [comment]
One important note about the sample XML that I provided immediately above: the `custom_js` attribute is alone on its line of text in my sample but that is not necessarily the case in an actual LastPass XML retrieved from the getaccts API at`https://lastpass.com/getaccts.php`.

So, any fix would also have to deal with things like:

    <login urid="xyz" attr1="abc" custom_js="var a=1; var b =2; if (a && b) b = 3;" attr2="xyz">

That means that a simple fix such as the following is not sufficient:

    [xml]$xml = $xmlPasteField.Text -replace ('custom_js=\".+\"', 'custom_js=""')

because it would result in the following (note: missing attr2):

    <login urid="xyz" attr1="abc" custom_js="">

when it should ideally result in the following (note: including the attr2):

    <login urid="xyz" attr1="abc" custom_js="" attr2="xyz">

Actually, this is why regex is almost always the wrong answer for XML manipulation, however we don't have valid XML here because LastPass emits it incorrectly, so options are limited. Sigh.

**Comment by john-aws** [comment]
So, a better test case would be as above but reformatted to more closely match what comes from getaccts:

    <response>
    <accounts accts_version="123" updated_enc="1" encrypted_username="redacted" cbc="1" pd="123456789" eu="1">
    <account name="redacted" urid="0" id="1234567890" url="68747470733a2f2f77656273657276696365732e77656265782e636f6d2f6d77333030302f6d7977656265782f64656661756c742e646f3f7369746575726c3d7765627365727669636573" m="1" http="0" fav="0" favico="0" autologin="0" basic_auth="0" group="redacted" fiid="1234567890" genpw="0" extra="" isbookmark="0" never_autofill="0" last_touch="1600000000" last_modified="1600000000" sn="0" realm="" sharedfromaid="" pwprotect="0" launch_count="0" username="redacted" groupid="78">
    <login urid="0" url="68747470733a2f2f77656273657276696365732e77656265782e636f6d2f6d77333030302f6d7977656265782f64656661756c742e646f3f7369746575726c3d7765627365727669636573"  submit_id="" captcha_id="" custom_js=" if(lploc==3){ var __u = document.getElementById('username'); var __f = document.getElementById('loginForm'); if (__u && __f && __u.tagName=='INPUT' && __f.tagName=='DIV' && typeof(lpcurruser)!='undefined') { __u.value = lpcurruser; } }" u="redacted" p="redacted" o="" method="post">
    <field name="screenName" type="text" value="redacted" />
    <field name="email" type="text" value="redacted" />
    </login>
    </account>
    </accounts>
    </response>

**Comment by FuLoRi** [comment]
Great examples and a good point about that regex capturing values following custom_js!

Assuming custom_js is never the last value in an account entry, we could simply add a space after the trailing double quotes in your regex example, like so:
`[xml]$xml = $xmlPasteField.Text -replace ('custom_js=\".+\" ', 'custom_js="" ')`

I'm not sure that's a safe assumption, though. Do you have any entries in your vault where that regex wouldn't work as intended?

**Comment by john-aws** [comment]
The custom_js attribute is not the last in any of my account entries so the entire XML parses cleanly with your proposed regex replace (tested using the paste method only). Actually it works cleanly with my original regex replace too, because none of the subsequent attributes in the `<login>` element are actually relevant to the analysis afaik.

**Comment by FuLoRi** [comment]
@john-aws:

I took a closer look at my vault in XML and found a custom_js entry. Mine parses just fine, though. You'll be able to spot the difference between yours and mine right away. Here's mine: 

```
custom_js="try { if (lpcurrpage.document.getElementById(&apos;ipcode&apos;) &amp;&amp; lpcurrpage.document.getElementById(&apos;ipcode&apos;).value == lpcurruser) { lpcurrpage.document.getElementById(&apos;ipcode&apos;).value = &apos;&apos;; } } catch (e) { }"
```

For whatever reason, it looks like the ampersands in your custom_js entries weren't converted to the corresponding HTML character codes. Or perhaps they were and then later converted back. Did you by chance open the XML in another program that may have converted the HTML character codes to their corresponding characters before saving the file?

I was about to implement the fix we discussed (after reading up on branches and pull requests, and installing Git Desktop), but now I wonder if it's even necessary.

Please let me know.

Thanks!

**Comment by john-aws** [comment]
That's a very good question. I collected the XML by visiting `https://lastpass.com/getaccts.php` and simply copy/pasting the result from there, rather than running your advertised `fetch` from the browser developer console. I did that copy/paste approach in order to avoid running arbitrary JavaScript from some random post on the internet ;-) It seems that this approach fails to encode `&` correctly.

Using your developer console approach does encodes each `&` to ` &amp;` and the XML parses cleanly with the original PS script. So I think my attempt to avoid running arbitrary JavaScript against my password manager was misguided and actually introduced the problem.

So, I think we can close this and my apologies for wasting your time.

**Comment by FuLoRi** [comment]
So **that's** what those three lines of JavaScript do. 😆 Mystery solved!

Thank you for all of your efforts to improve this script! I very much appreciate it. 😁 From my perspective, this was time well spent. I learned how to open and close a branch and a pull request, and why Steve had us use the fetch in the developer console.

Have a great day!
