### ISSUE TITLE
Run-Time Error

### ISSUE THREAD

**Issue by j8732** [FuLoRi/Analyze-LastPassVaultGUI#9]
I get the following error when running.  Since I already deleted my LastPass account, I can't re-generate the .xml.  The file that I save starts with an <accounts> tag.  Am I missing data that should have been before this? 

Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "This document already has a
'DocumentElement' node."
At C:\Users\xxx\OneDrive\Documents\computer\lastpass\Analyze-LastPassVault.ps1:315 char:17
+                 [xml]$xml = Get-Content -Path $InFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "This document already has a
'DocumentElement' node."
At C:\Users\xxx\OneDrive\Documents\computer\lastpass\Analyze-LastPassVault.ps1:328 char:3
+         [xml]$xml = Get-Content -Path $InFile
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

**Comment by j8732** [comment]
Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "This document already has a
'DocumentElement' node."
At C:\Users\xxx\OneDrive\Documents\computer\lastpass\Analyze-LastPassVault.ps1:315 char:17
+                 [xml]$xml = Get-Content -Path $InFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

Cannot convert value "System.Object[]" to type "System.Xml.XmlDocument". Error: "This document already has a
'DocumentElement' node."
At C:\Users\xxx\OneDrive\Documents\computer\lastpass\Analyze-LastPassVault.ps1:328 char:3
+         [xml]$xml = Get-Content -Path $InFile
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastToXmlDocument

**Comment by FuLoRi** [comment]
@j8732: Yes, it seems that the XML you have is malformed. The XML should start out like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<response>
```

After that is `accounts`, which contains the individual `account` entries.

If you make a copy of your XML file, edit it as needed to match that format, and try importing it again, you may have success.
